version: '3.7'

services:
  # Override bahmni-web to include TIHUT branding and direct access
  bahmni-web:
    ports:
      - '8090:8091'
    volumes:
      - "${CONFIG_VOLUME:?}:/usr/local/apache2/htdocs/bahmni_config/:ro"
      - './custom-config/bahmni_config:/usr/local/apache2/htdocs/bahmni_config/custom:ro'
      - './custom-config/images:/usr/local/apache2/htdocs/bahmni_config/images:ro'
    environment:
      - ORGANIZATION_NAME=TIHUT Clinic
      - HOSPITAL_NAME=TIHUT Clinic
      - LOGO_PATH=/bahmni_config/images/tihut-logo.jpg

  # Override bahmni-config to include TIHUT customizations
  bahmni-config:
    volumes:
      - '${CONFIG_VOLUME:?}:/usr/local/bahmni_config'
      - './custom-config/bahmni_config:/usr/local/bahmni_config/custom:ro'
      - './custom-config/images:/usr/local/bahmni_config/images:ro'

  # Override OpenMRS to include TIHUT configurations
  openmrs:
    environment:
      - ORGANIZATION_NAME=TIHUT Clinic
      - HOSPITAL_NAME=TIHUT Clinic

  # Override implementer-interface to include TIHUT branding
  implementer-interface:
    volumes:
      - './custom-config/bahmni_config:/usr/local/apache2/htdocs/bahmni_config/custom:ro'
      - './custom-config/images:/usr/local/apache2/htdocs/bahmni_config/images:ro'

  # Override reports to include TIHUT branding
  reports:
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-queued-reports:/home/bahmni/reports"
      - './custom-config/images:/etc/bahmni_config/images:ro'
      - './custom-config/bahmni_config:/etc/bahmni_config/custom:ro'
    environment:
      - ORGANIZATION_NAME=TIHUT Clinic
      - HOSPITAL_NAME=TIHUT Clinic
