version: '3.7'

services:
  # Override proxy to use different port to avoid conflicts
  proxy:
    ports:
      - '8080:80'
      - '443:443'
  # Override bahmni-config to include custom configurations
  bahmni-config:
    volumes:
      - '${CONFIG_VOLUME:?}:/usr/local/bahmni_config'
      - './custom-config/bahmni_config:/usr/local/bahmni_config/custom:rw'
      - './custom-config/images:/usr/local/bahmni_config/images:ro'

  # Override bahmni-web to include custom CSS and configurations
  bahmni-web:
    ports:
      - '8090:8091'
    volumes:
      - "${CONFIG_VOLUME:?}:/usr/local/apache2/htdocs/bahmni_config/:ro"
      - './custom-config/bahmni_config:/usr/local/apache2/htdocs/bahmni_config/custom:rw'
      - './custom-config/images:/usr/local/apache2/htdocs/bahmni_config/images:ro'

  # Override OpenMRS to include custom configurations
  openmrs:
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-lab-results:/home/bahmni/uploaded_results"
      - "bahmni-uploaded-files:/home/bahmni/uploaded-files"
      - 'bahmni-patient-images:/home/bahmni/patient_images'
      - 'bahmni-document-images:/home/bahmni/document_images'
      - 'bahmni-clinical-forms:/home/bahmni/clinical_forms'
      - 'configuration_checksums:/openmrs/data/configuration_checksums'
      - 'sms-token:/openmrs/data/sms-token'

  # Override implementer-interface to include custom configurations
  implementer-interface:
    volumes:
      - './custom-config/bahmni_config:/usr/local/apache2/htdocs/bahmni_config/custom:ro'
      - './custom-config/images:/usr/local/apache2/htdocs/bahmni_config/images:ro'

  # Override reports to include custom branding
  reports:
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-queued-reports:/home/bahmni/reports"
      - './custom-config/images:/etc/bahmni_config/images:ro'
      - './custom-config/bahmni_config:/etc/bahmni_config/custom:ro'
